{
 "title": "PAIS NVIDIA vGPU Metrics",
 "description": "vGPU metrics from NVIDIA DCGM Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_endpoint",
    "label": "Model Endpoint",
    "query": {
     "query": "label_values(kube_node_labels{label_nvidia_com_gpu_present=\"true\"},label_pais_vmware_com_modelendpoint_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"},node)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "vGPU licensed?",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_VGPU_LICENSE_STATUS{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"} * 1000000",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"} * 1000000",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_FB_USED{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  }
 ]
}