{
 "title": "PAIS Llama.CPP ModelEndpoints",
 "description": "Llama.cpp ModelEndpoints metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_endpoint",
    "label": "Model Endpoint",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"pais\", label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\"},label_pais_vmware_com_modelendpoint_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Generation Throughput (tokens/s)",
   "type": "timeseries",
   "description": "The current throughput rate (tokens/s) for Generation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:predicted_tokens_seconds, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Average Prompt Throughput (tokens/s)",
   "type": "timeseries",
   "description": "The current throughput rate (tokens/s) for Prompt.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:prompt_tokens_seconds, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Total Generation Tokens",
   "type": "timeseries",
   "description": "Total number of tokens generated by the model across all requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:tokens_predicted_total, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Total Prompt Tokens",
   "type": "timeseries",
   "description": "Total number of tokens processed (prompt tokens) since server start.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:prompt_tokens_total, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Requests processing",
   "type": "timeseries",
   "description": "Number of requests currently being actively processed by the engine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:requests_processing, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Requests deferred",
   "type": "timeseries",
   "description": "Number of deferred requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:requests_deferred, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Generation process time",
   "type": "timeseries",
   "description": "Total Generation processing time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:tokens_predicted_seconds_total, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Prompt process time",
   "type": "timeseries",
   "description": "Total Prompt processing time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "(label_replace(llamacpp:prompt_seconds_total, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Generation process rate",
   "type": "timeseries",
   "description": "Generation processing rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "((label_replace(rate(llamacpp:tokens_predicted_seconds_total[5m]), \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"})",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  },
  {
   "title": "Prompt process rate",
   "type": "timeseries",
   "description": "Prompt processing rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "(label_replace(rate(llamacpp:prompt_seconds_total[5m]), \"node_ip\", \"$1\", \"instance\", \"(.*):.*\") * on(node_ip) group_left(node) label_replace(kube_node_info, \"node_ip\", \"$1\", \"internal_ip\", \"(.*)\")) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_type) kube_node_labels{label_pais_vmware_com_modelendpoint_engine=\"LlamaCPP\", label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}}"
    }
   ]
  }
 ]
}