{
 "title": "PAIS NVIDIA GPU Metrics",
 "description": "GPU metrics from NVIDIA DCGM Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_endpoint",
    "label": "Model Endpoint",
    "query": {
     "query": "label_values(kube_node_labels{label_nvidia_com_gpu_present=\"true\"},label_pais_vmware_com_modelendpoint_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"},node)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_MEMORY_TEMP{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Graphics Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU PCIe Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_PROF_PCIE_TX_BYTES{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Interface Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_PROF_DRAM_ACTIVE{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU PCIe Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_PROF_PCIE_RX_BYTES{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_FB_USED{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"} * 1000000",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"} * 1000000",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU NVLink Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max(label_replace(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=~\"${node}\", gpu=~\"${gpu}\"}, \"node\", \"$1\", \"Hostname\", \"(.*)\")) by (node, gpu) * on(node) group_left(label_pais_vmware_com_modelendpoint_name, label_pais_vmware_com_modelendpoint_engine) kube_node_labels{label_pais_vmware_com_modelendpoint_name=~\"${model_endpoint}\"}",
     "legendFormat": "{{label_pais_vmware_com_modelendpoint_name}}: {{node}} : {{gpu}}"
    }
   ]
  }
 ]
}